In [2]:
import numpy as np

def create_numpy_array():
    """ Returns a numpy array
    >>> create_numpy_array()
    array([1,2,3,4,5])
    """
    return np.array([1,2,3,4,5])




In [3]:
create_numpy_array()

array([1, 2, 3, 4, 5])

In [4]:

python_list = list(range(5))
numpy_array = np.array(range(5))
python_list, numpy_array

([0, 1, 2, 3, 4], array([0, 1, 2, 3, 4]))

In [5]:
size = (1,2,3)
np.random.random_sample(size=size)

array([[[0.09292281, 0.50538374, 0.61721907],
        [0.73906124, 0.81093548, 0.69684967]]])

In [6]:
b = np.array([[1,2,3,4], [4,5,6,7]])

In [7]:
b.shape

(2, 4)

In [8]:
b.dtype

dtype('int32')

In [9]:
b.size

8

In [10]:
b.ndim

2

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
c = np.full((5,6), 7)

In [17]:
c

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

In [18]:
c*10

array([[70, 70, 70, 70, 70, 70],
       [70, 70, 70, 70, 70, 70],
       [70, 70, 70, 70, 70, 70],
       [70, 70, 70, 70, 70, 70],
       [70, 70, 70, 70, 70, 70]])