In [11]:
import numpy as np

def create_numpy_array():
    """ Returns a numpy array
    >>> create_numpy_array()
    array([1,2,3,4,5])
    """
    return np.array([1,2,3,4,5])




In [12]:
create_numpy_array()

array([1, 2, 3, 4, 5])

In [3]:

python_list = list(range(5))
numpy_array = np.array(range(5))
python_list, numpy_array

([0, 1, 2, 3, 4], array([0, 1, 2, 3, 4]))

In [5]:
size = (1,2,3)
np.random.random_sample(size=size)

array([[[0.87053786, 0.45961082, 0.5596455 ],
        [0.53699079, 0.28697581, 0.11555825]]])